### ISSUE TITLE
Matching groups?

### ISSUE THREAD

**Issue by victorperin** [kas-elvirov/regexify-string#10]
I couldn't find a way to match groups. For example:

```jsx
regexifyString({
    pattern: /\[(?<id>.+)\]\{(?<name>.+)\}/g,
    decorator: (id, name) => (<item b={id} c={name} />),
    input: 'a[b]{c}',
})

// to output:
// [ 'a', <item b='b' c='c' />, '']
```

Is this possible?

**Comment by G1K** [comment]
https://github.com/kas-elvirov/regexify-string/blob/master/src/index.ts#L24

You can pass the whole result here with the third argument, the groups will be next after the 0 element of the array.
```
        const decoratedMatch = decorator(match, matchIndex, result);
```

**Comment by kas-elvirov** [comment]
@victorperin @G1K is this functionality still needed?

**Comment by G1K** [comment]
this function will definitely be useful, but it is possible to design it in a more beautiful way. My solution suits me and I'm already using it).

**Comment by kas-elvirov** [comment]
@G1K could you share your version?

**Comment by G1K** [comment]
The line from the message above is already my solution) `result` contains the result of exec , it will already contain named groups if it was in the regular expression.

```
        const decoratedMatch = decorator(match, matchIndex);
>>
        const decoratedMatch = decorator(match, matchIndex, result);
```
`result.groups`
