### ISSUE TITLE
regexifString crash at some scenarios

### ISSUE THREAD

**Issue by arunmir** [kas-elvirov/regexify-string#6]
In some scenarios, the regexifString crashes the browser. 
ex: 

```
console.log(

    "regexifyString test",
    regexifyString({
      pattern: /.*/gim,
      decorator: (match, index) => {return 'ReplaceMe';},
      input: "This is a test",
    })

 );
```

I did a simple debug in the function implementation and found `if (match === "") break` inside the 

```
while (result !== null) {

    const matchStartAt = result.index;
    const match = result[0];
   ...

}
```

solve the issue. Can you please consider including this fix?

**Comment by artem-solovev** [comment]
Dear  @arunmir , hi

Thank you for your report, i will fix it by the end of the week
Have a good day)

**Comment by artem-solovev** [comment]
Dear @arunmir hi.

Could you review [this PR](https://github.com/artem-solovev/regexify-string/pull/8)

If everything as you need we will release it then

**Comment by kas-elvirov** [comment]
@arunmir im closing this issue because of long silence on code-review
